# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 305aa8b2e739cd00938ea8317360d93c2c6de85ccf7ab076100c6e9daf5f4fb280650e3e279b2104bded97778cd96c2ffbb1978cfc3fb22bab24b50b1a29c880

test:
  secret_key_base: 136cbb694d46f937761e27d949c61469b73d7030f1097b7976bbb651f72edcc4950afed893425b998565dc3c7e20104d5125a77c0e3ce63ab97c3c3c2a5aa01c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
